### ISSUE TITLE
[Feature]SELECT QueryMethod 테스트 하기 기능 추가

### ISSUE THREAD

**Issue by Wondear** [JPA-TWO/jpa-data#4]
# 기능 추가/수정 요청
-QueryMethod 테스트 하기 기능 추가

## TO-DO
- [ ] MenuController에 /menu/querymethod 를 처리하는 메소드 작성
- [ ] 쿼리 메소드 작성
- [ ] 서비스 처리 후 확인
